<?php
/**
 * Created by PhpStorm.
 * User: zhaoj
 * Date: 2019/4/19
 * Time: 17:40
 */

namespace api\controllers;


use yii\data\ActiveDataProvider;
use yii\rest\ActiveController;

class ArticleController extends ActiveController
{
    public $modelClass = 'common\models\Article';

    public function actions()
    {
        $actions = parent::actions();
        unset($actions["index"]);
        return $actions; // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $modelClass = $this->modelClass;
        return new ActiveDataProvider([
            "query" => $modelClass::find()->asArray(),
            "pagination" => ["pageSize" => 5]
        ]);
    }
}