<?php
/**
 * Created by PhpStorm.
 * User: zhaoj
 * Date: 2019/4/19
 * Time: 17:40
 */

namespace api\controllers;


use backend\models\Adminuser;
use common\models\Article;
use yii\data\ActiveDataProvider;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\QueryParamAuth;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\rest\ActiveController;
use yii\web\ForbiddenHttpException;
use yii\web\Response;

class ArticleController extends ActiveController
{
    public $modelClass = 'common\models\Article';

    // 请求参数认证方式
    public function behaviors()
    {
        return ArrayHelper::merge(parent::behaviors(), [
            'authenticatior' => [
                'class' => QueryParamAuth::className()
            ]
        ]);
    }

    // 校验权限
    public function checkAccess($action, $model = null, $params = [])
    {
        //对ActiveControllers类中默认实现了的方法进行权限设置
        if ($action === 'view') {
            if (\Yii::$app->user->can('ArticleViewer')) {
                return true;
            }
        }

        if ($action === 'view' || $action === 'update' || $action === 'delete'
            || $action === 'create' || $action === 'index') {
            if (\Yii::$app->user->can('ArticleAdmin')) {
                return true;
            }
        }

        throw new ForbiddenHttpException('对不起，你没有进行该操作的权限。');

    }

    // HTTP BASIC认证方式
//     public function behaviors()
//     {
//          return ArrayHelper::merge(parent::behaviors(), [
//             'authenticatior' => [
//                 'class' => HttpBasicAuth::className(),
//                 'auth' => function ($username, $password) {
//                         $user = Adminuser::find()->where(['username' => $username])->one();
//                         if ($user->validatePassword($password)) {
//                             return $user;
//                         }
//                         return null;
//                         }
//                      ]
//             ]);
//     }

    public function actions()
    {
        $actions = parent::actions();
        unset($actions["index"]);
        return $actions; // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        if (!\Yii::$app->user->can('ArticleAdmin')) {
            throw new ForbiddenHttpException('对不起，你没有进行该操作的权限。');
        }
        \Yii::$app->response->format = Response::FORMAT_JSON;
        $modelClass = $this->modelClass;
        return new ActiveDataProvider([
            "query" => $modelClass::find()->asArray(),
            "pagination" => ["pageSize" => 5]
        ]);
    }

    // 增加搜索文章的功能
    public function actionSearch()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        return Article::find()->where(['like', 'title', \Yii::$app->request->post("keyword")])->all();
    }
}