<?php
/**
 * Created by PhpStorm.
 * User: zhaoj
 * Date: 2019/4/19
 * Time: 17:40
 */

namespace api\controllers;


use backend\models\Adminuser;
use common\models\Article;
use yii\data\ActiveDataProvider;
use yii\filters\auth\HttpBasicAuth;
use yii\filters\auth\QueryParamAuth;
use yii\filters\VerbFilter;
use yii\helpers\ArrayHelper;
use yii\rest\ActiveController;
use yii\web\Response;

class ArticleController extends ActiveController
{
    public $modelClass = 'common\models\Article';

    // 请求参数认证方式
//    public function behaviors()
//    {
//        return ArrayHelper::merge(parent::behaviors(), [
//            'authenticatior' => [
//                'class' => QueryParamAuth::className()
//            ],
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'search' => ['post'],
//                ],
//            ],
//        ]);
//    }

     // HTTP BASIC认证方式
//     public function behaviors()
//     {
//          return ArrayHelper::merge(parent::behaviors(), [
//             'authenticatior' => [
//                 'class' => HttpBasicAuth::className(),
//                 'auth' => function ($username, $password) {
//                         $user = Adminuser::find()->where(['username' => $username])->one();
//                         if ($user->validatePassword($password)) {
//                             return $user;
//                         }
//                         return null;
//                         }
//                      ]
//             ]);
//     }

    public function actions()
    {
        $actions = parent::actions();
        unset($actions["index"]);
        return $actions; // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        $modelClass = $this->modelClass;
        return new ActiveDataProvider([
            "query" => $modelClass::find()->asArray(),
            "pagination" => ["pageSize" => 5]
        ]);
    }

    // 增加搜索文章的功能
    public function actionSearch()
    {
        \Yii::$app->response->format = Response::FORMAT_JSON;
        return Article::find()->where(['like', 'title', \Yii::$app->request->post("keyword")])->all();
    }
}